module.exports = {
  "year": 2023,
  "categories": [
    {
      title: "Corporate Sponsors",
      level: 1,
      amount: "$10,000 or more",
      slug: "corporate",
      sponsors: [],
    },
    {
      title: "Platinum Sponsors",
      level: 2,
      amount: "$5000 – $9999",
      slug: "platinum",
      sponsors: [
        { name: "Warner Robins Parks & Recreation Department", location: "Host Agency", img: "/images/sponsors/WRPR-High-Res-2x.png", },
      ],
    },
    {
      title: "Gold Sponsors",
      level: 3,
      amount: "$2500 – $4999",
      slug: "gold",
      sponsors: [
        { name: "The Miles Group", location: "Snellville", },
        { name: "First Christian Church", location: "Winder", },
        { name: "Houston Healthcare", img: "/images/sponsors/HHC-new-logo-2016_resized.png", url: "https://www.hhc.org/", },
        { name: "EPIC Health Advisors", location: "Gray", img: "/images/sponsors/epic-health-logo_resized.png", url: "https://epichealthadvisors.com/", },
      ],
    },
    {
      title: "Silver Sponsors",
      level: 4,
      amount: "$1000 – $2499",
      slug: "silver",
      sponsors: [
        { name: "Georgia Health Care Association", },
        { name: "Tori & David Stivers (In memory of Pinkie Henry)", location: "Peachtree City", },
        { name: "Clover Health, LLC", location: "Atlanta", },
      ],
    },
    {
      title: "Bronze Sponsors",
      level: 5,
      amount: "$500 – $999",
      slug: "bronze",
      sponsors: [
        { name: "Comfort Inn and Suites Hwy 247", location: "Warner Robins", },
        { name: "Tom Gill", location: "Madison, AL", },
        { name: "Grovania United Methodist Church", },
        { name: "Ookla", location: "Seattle, WA", img: "/images/sponsors/ookla-logo.png", url: "https://www.ookla.com/", },
        { name: "Jacuzzi Bath Remodels of Middle GA", location: "Dublin", },
      ],
    },
    {
      title: "Torch Club",
      level: 6,
      amount: "$100 – $499",
      slug: "torch",
      sponsors: [
        { name: "Robert & Faye Buckham", location: "Woodstock", },
        { name: "Jewel Crews", location: "Waycross", },
        { name: "Ed Freeman", location: "Virginia", },
        { name: "Rebecca Hamilton", location: "Byron", },
        { name: "Linda Lowery", location: "Smyrna", },
        { name: "Gladys Mixon", location: "Rome", },
        { name: "Jim & Miriam Novak", location: "Bainbridge", },
        { name: "Carol Waddell", location: "Rome", },
        { name: "Bonnie Romines", location: "Warner Robins", },
        { name: "Weiland A. Henry, III", location: "Seale, AL", },
        { name: "Atlanta Promo - A Group Atlanta Company", location: "Roswell", },
        { name: "George & Charlotte Zubowicz", location: "Warm Springs", },
        { name: "George W Marlow III", location: "Lawrenceville", },
        { name: "Marshall Martin", location: "Lady Lake, FL", },
        { name: "Don Tate", location: "Bonaire", },
      ],
    },
    {
      title: "Friends",
      level: 7,
      amount: "$25 – $99",
      slug: "friends",
      sponsors: [
        { name: "Mike Jewell", location: "Loganville", },
        { name: "Roscoe Googe", location: "Marietta", },
        { name: "Vincent Marchionna", location: "St Simons", },
        { name: "B & W Recreation Center", location: "Warner Robins", },
        { name: "Toni Pomerene", location: "Athens", },
        { name: "Cherry Stephens", location: "Winder", },
        { name: "Robert Jackson", location: "Hoschton", },
        { name: "William Astary", location: "Tybee Island", },
        { name: "Ed & Karen Brown", location: "Colbert", },
        { name: "Ray Cipollini", location: "Bluffton, SC", },
        { name: "Neil Coleman", location: "Evans", },
        { name: "Warren Griffin", location: "Macon", },
        { name: "Felicia Mayfield", location: "Lithonia", },
        { name: "Dennis Meinert", location: "Chattanooga, TN", },
        { name: "Mary S Newton", location: "Tucker", },
        { name: "Vermel Thomas", location: "Dublin", },
        { name: "Amy Tonsits", location: "Thomasville", },
        { name: "Don Albino", location: "Johns Creek", },
        { name: "Mohamed Ali", location: "Fayetteville", },
        { name: "Jonathan Bortner", location: "Mt Pleasant, SC", },
        { name: "Richard Cook", location: "Macon", },
        { name: "Robert Cresswell", location: "Greensboro", },
        { name: "Mary Ealer", location: "Warner Robins", },
        { name: "Dennis Evans", location: "Warner Robins", },
        { name: "David Jones", location: "Stone Mountain", },
        { name: "Nancy Lewis", location: "Greensboro", },
        { name: "Stanley Manous", location: "Griffin", },
        { name: "Bob McCoid", location: "West Alexander, PA", },
        { name: "Randall Neff", location: "Byron", },
        { name: "Jim Powell", location: "Pratville, AL", },
        { name: "Barbara Reddick", location: "Remlap, AL", },
        { name: "Ahmad Shabazz", location: "Starr, SC", },
        { name: "Glenda Davis", location: "Cochran ", },
        { name: "AAB Human Resources Services, LLC", location: "Marietta", },
        { name: "Alan Griswold", location: "Warner Robins", },
        { name: "Steven Hancock", location: "Statesboro", },
        { name: "Ned Sanders", location: "Warner Robins", },
      ],
    },
  ],
};
