media:
  - name: Images
    input: src/images
    output: src/images
  - name: Files
    input: src/files
    output: src/files
content:
  - name: site-notice
    label: Site-wide Notice
    type: file
    path: src/pages/_includes/site-wide-notice.md
    fields:
      - name: notice
        label: Notice
        type: rich-text
        description: This notice shows up on every page of the site. Useful for very important information.
      - name: show
        label: Show
        type: boolean
        description: Turn this off to hide the notice.
  - name: event-rules
    label: Event Rules
    type: collection
    path: src/pages/events
    primary: title
    filename: "{primary}.md"
    view:
      fields: [ primary, title, published, updated ]
      sort: [ primary, updated ]
    fields:
      - name: title
        label: Title
        type: string
      - name: published
        label: Published
        type: boolean
        default: true
      - name: updated
        label: Last Updated
        type: date
      - name: body
        label: Body
        type: rich-text
