media:
  - name: Images
    input: src/images
    output: /images
  - name: Files
    input: src/files
    output: /files
content:
  - name: event-rules
    label: Event Rules
    type: collection
    path: src/pages/events
    view:
      fields: [ title, published, updated ]
      sort: [ title, updated ]
    fields:
      - name: title
        label: Title
        type: string
      - name: updated
        label: Last Updated
        type: date
      - name: published
        label: Published
        type: boolean
        default: true
      - name: body
        label: Body
        type: rich-text

