media:
  - name: Images
    input: src/images
    output: src/images
  - name: Files
    input: src/files
    output: src/files
content:
  - name: site-configuration
    label: Site configuration
    type: file
    path: src/pages/_data/configuration.json
    fields:
      - name: site-notice-enable
        label: Enable Site-wide notice
        type: boolean
        description: Enable or disable the site-wide notice.
      - name: site-notice-body
        label: Site-wide notice
        type: rich-text
        description: This notice will appears at the top of every page. Useful for very important information.
  - name: sponsors
    label: Sponsors
    type: collection
    description: Delete the sponsor's tier to remove them from the listing. Do not delete the entire entry.
    path: src/pages/sponsors
    filename: "{fields.name}-{fields.location}.md"
    fields:
      - name: name
        label: Name
        type: string
      - name: location
        label: Location
        type: string
        description: Usually formatted as `City, ST`, or just `City` if state is GA
      - name: tier
        label: Sponsorship Tier
        type: select
        description: Delete the tier to remove the sponsor from the listing.
        options:
          values:
            - value: friends
              label: Friends
            - value: torch
              label: Torch Club
            - value: bronze
              label: Bronze
            - value: silver
              label: Silver
            - value: gold
              label: Gold
            - value: platinum
              label: Platinum
            - value: corporate
              label: Corporate
      - name: link
        label: Link
        type: string
      - name: image
        label: Image
        type: image
        description: For company logos
      - name: permalink
        label: Permalink
        type: boolean
        default: false
        hidden: true
    view:
      fields: [ name, location, tier.label, link, image ]
      primary: name
      sort: [ name, tier.value, location ]
  - name: sponsorship-tiers
    label: Sponsorship Tiers
    type: collection
    path: src/pages/sponsorship-tiers
    filename: "{fields.slug}.md"
    fields:
      - name: tiers
        label: Tiers
        type: object
        list: true
        fields:
        - name: title
          label: Title
          type: string
        - name: slug
          label: Slug
          type: string
        - name: amount
          label: Amount
          type: string
  - name: event-rules
    label: Event Rules
    type: collection
    path: src/pages/events
    filename: "{primary}.md"
    view:
      fields: [ title, published, updated ]
      primary: title
      sort: [ title, updated ]
    fields:
      - name: title
        label: Title
        type: string
      - name: published
        label: Published
        type: boolean
        default: true
      - name: updated
        label: Last Updated
        type: date
      - name: body
        label: Body
        type: rich-text
